[feat]: 타임스탬프 작성 API
nneaning/meaning_Server pull request #26
Opened 2021-01-05 06:52 UTC by tributetothemoon

## 작업사항

타임스탬프를 작성하는 API 를 생성했습니다.
- 인증 시간, 글 내용, 사진을 바디에 담아 요청합니다.
- 생성된 타임스탬프의 PK, 인증 시간, 글 내용, 사진의 URL, 성공/지각 여부를 리턴합니다.

## 사용방법
[API 명세서](https://github.com/nneaning/meaning_Server/wiki/%ED%83%80%EC%9E%84%EC%8A%A4%ED%83%AC%ED%94%84-%EC%9E%91%EC%84%B1)

### 희망 리뷰 완료일

2021.01.05

### 관계된 이슈, PR 

#9

2021-01-05 08:54 UTC, epitoneproject requested changes
일단 개인적으로 생각하는 부분들을 적어봤어!! 한번 살펴봐주라!!

2021-01-05 08:54 UTC, epitoneproject commented on controller/timeStampController.js
> +      const user = await userService.checkUserId(req.decoded.id);
미들웨어로 user에 대한 정보를 받아오기 때문에 따로 유저의 id를 확인할 필요는 없을 것 같아! user의 id가 없다면, 미들웨어에서 걸러졌을거야!

2021-01-05 08:54 UTC, epitoneproject commented on controller/timeStampController.js
> +dayjs.extend(require('dayjs/plugin/duration'));
dayjs.extend(require('dayjs/plugin/customParseFormat'));
dayjs.extend(require('dayjs/plugin/duration'));

이 두개를 한 줄로 합칠 수 없을까?

2021-01-05 08:54 UTC, epitoneproject commented on controller/timeStampController.js
> +      const timeDiff = dayjs.duration(requestedTime.diff(targetTime)).asMinutes();
변수명에서 약어는 최대한 지양해보는건 어떨까!?

2021-01-05 08:54 UTC, epitoneproject commented on controller/timeStampController.js
> +      }
여기서 성공, 지각, 불참해서 3가지 데이터를 나눠야할 것 같은데 2개 말고 3개로 나눠보는건 어떨까?

2021-01-05 08:54 UTC, epitoneproject commented on controller/timeStampController.js
> +
여기서 status는 무엇을 의미하는걸까?

2021-01-05 08:54 UTC, epitoneproject commented on controller/timeStampController.js
> +            },
타임스탬프 정보를 저장하고, 이 정보들을 다시 전해주는 이유가 궁금해!

2021-01-05 08:54 UTC, epitoneproject commented on controller/timeStampController.js
> +            responseMessage.INTERNAL_SERVER_ERROR,
나는 responseMessage를 500에러를 받으면, CREATE_TIMESTAMP_FAIL 이렇게 작성해보는 걸 생각했는데 어떤게 더 좋은 것 같아??

2021-01-05 08:54 UTC, epitoneproject commented on service/timeStampService.js
> +      UserId: userId,
controller에선 user.id를 인자로 넣어주는데, Service에는 userId로 받아서 뭔가 통일을 시켜주는게 좋아보이지 않을까 개인적으로 생각해봤어!!

2021-01-05 08:57 UTC, tributetothemoon commented on controller/timeStampController.js
> +      const user = await userService.checkUserId(req.decoded.id);
아이디를 거르기위함이 아니라 user의 기상 시간이 필요해서 입니다! id를 이용해서 User 인스턴스를 받아와야하는데 checkUserId가 그 기능을 수행하길래 가져다 썼습니다!

2021-01-05 09:16 UTC, epitoneproject commented on controller/timeStampController.js
> +      const user = await userService.checkUserId(req.decoded.id);
아하! 그렇다면 checkUserId에서 지금은 비밀번호와 salt값 빼고 모든 데이터를 다 가져오는데, 지금 활용하려고 하는건 wakeUpTime 데이터만 가져오면 되니까! service에서 wakeUpTime만 가져오는걸로 변경해보는건 어떨까!?

2021-01-05 09:42 UTC, tributetothemoon commented on controller/timeStampController.js
> +      const timeDiff = dayjs.duration(requestedTime.diff(targetTime)).asMinutes();
수정했습니다 👍

2021-01-05 10:34 UTC, epitoneproject commented on controller/timeStampController.js
> +      const requestedTime = dayjs(dateTime);
변수 requestedTime에서 dayjs(dateTimeFormat.DATETIME)으로 적어야 적용되는건 아닌거지?

2021-01-05 10:48 UTC, tributetothemoon commented on controller/timeStampController.js
> +      const requestedTime = dayjs(dateTime);
응! dateTimeFormat.DATETIME은 'YYYY-MM-DD HH:mm:ss'이고, dateTime은 요청 바디에 붙어온 실제 시간(ex. 2021-01-15 19:48:13)을 뜻해!

2021-01-05 10:48 UTC, tributetothemoon commented on controller/timeStampController.js
> +            responseMessage.INTERNAL_SERVER_ERROR,
좋은 생각입니다!

2021-01-05 11:55 UTC, tributetothemoon commented on controller/timeStampController.js
> +            },
보내지 않도록 수정하였습니다 :)

2021-01-05 11:55 UTC, tributetothemoon commented on service/timeStampService.js
> +      UserId: userId,
통일했습니다~

2021-01-05 15:20 UTC, tributetothemoon commented on controller/timeStampController.js
> +dayjs.extend(require('dayjs/plugin/duration'));
[커밋 내역](https://github.com/nneaning/meaning_Server/pull/26/commits/9ed988d3dfa0168692e544bdd948342208f700f8)
로 인해 삭제할 수 있을 것으로 보임!

2021-01-05 15:46 UTC, tributetothemoon commented on controller/timeStampController.js
> +      const timeDiff = dayjs.duration(requestedTime.diff(targetTime)).asMinutes();
[커밋 내역](https://github.com/nneaning/meaning_Server/pull/26/commits/c69fdc599367e119368d74c88d4c3fa60103cbf0)

2021-01-05 15:47 UTC, tributetothemoon commented on controller/timeStampController.js
> +            },
[커밋 내역](https://github.com/nneaning/meaning_Server/pull/26/commits/b27baed5d14ff229fd41f505c5d9cdd1e0101cfd)

2021-01-05 15:47 UTC, tributetothemoon commented on controller/timeStampController.js
> +            responseMessage.INTERNAL_SERVER_ERROR,
[커밋 내역](https://github.com/nneaning/meaning_Server/pull/26/commits/91e27bf2479dca2c5e61d6534d04f64a41c14b44)

2021-01-06 00:34 UTC, epitoneproject reviewed
너무 고생많았어 ㅎㅎㅎㅎㅎ

2021-01-06 05:03 UTC, merged